### ISSUE TITLE
[FEA] Count aggregate on all charts

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cuxfilter#147]
I wish cuxfilter would have an option to do an `aggregate_fn`, on an `aggregate_col` like count, on `stacked_line` as it does with `heat_map`

Right now, there is no good way to do this if you want to cross filter on the original data, as you have to create a new dataframe with a groupby.

**Comment by AjayThorve** [comment]
In the heatmap, the x and y axis are separate columns and the aggregate column another column in the dataset (total 3 columns required). The line chart is basically just x and y axis (2 columns), and plots every single point for x vs y.  Adding aggregate fn for a x-y line chart doesnt make sense in this case. 


if what you are aiming for is aggregated line chart(similar to bar charts, but with a line trajectory instead of individual bars), have a look at the bokeh line chart implementation - https://docs.rapids.ai/api/cuxfilter/stable/charts/bokeh_charts.html#id1

Closing the issue.
