### ISSUE TITLE
[BUG] Same plot type not plotted in multi-plot dashboard

### ISSUE THREAD

**Issue by esnvidia** [rapidsai/cuxfilter#316]
Plotting two plots of the same type is not working for displaying both plots in the dashboard, only the last plot will plot

Here's the base case:
![image](https://user-images.githubusercontent.com/80840697/130126263-1041845c-69ea-4502-a7b1-e1e856b0e2b0.png)

Now when we change one of the plots to a bokeh line chart.. the names are different and the second plot will show.

![image](https://user-images.githubusercontent.com/80840697/130126210-ac7c39be-4f48-4990-be37-1030cba973db.png)

Notice how the name of the charts is the same....
In `dashboard.py` https://github.com/rapidsai/cuxfilter/blob/branch-21.10/python/cuxfilter/dashboard.py#L190
```
        for chart in charts:
            self._charts[chart.name] = chart
            chart.initiate_chart(self)
            chart._initialized = True
```
So the same chart name is causing an overwrite in `self._charts[chart.name]`

**Comment by AjayThorve** [comment]
Hey @esnvidia , thanks for raising the issue. 

You are right, that infact is the expected behavior as of now. 

The names of scatter charts currently are saved internally as "{x}_{y}_scatter". Both your charts had same exact x and y coordinates, which is why the override happened. 

This should be an easy fix, renaming scatter names to "{x}_{y}_{aggregate_col}_scatter", so that charts that differ by aggregate_col also co-exist. I'll create a PR to fix it soon.
