### ISSUE TITLE
[BUG] Inconsistent API 

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cuxfilter#408]
**Describe the bug**
Hi! I have noticed that some properties that were accessible before are now not available anymore.

That is fine. But I have noticed a component where these properties are yet accesible.

For instance. Before, I could do:

```python
import cuxfilter as cux
from cuxfilter.charts.datashader import line

# some code here

_ = cux.DataFrame.from_dataframe(heartbeats_cudf).dashboard([line_cux])
line_cux.chart.title.text = 'ECG stream'
line_cux.chart.title.align = 'center'
line_cux.chart.width = WIDTH
line_cux.chart.height = HEIGHT
line_cux.view()[0]
```

And now, I cannot access `cux.chart.title.text` nor the other properties. That is fine.

But somehow, in the following type of chart, I can still access some of those properties.

```python
from cuxfilter.charts import bar

# some code here

_ = cux.DataFrame.from_dataframe(lengths_cudf).dashboard([bar_cux])
bar_cux.chart.title.text = 'Segment lengths'
bar_cux.chart.title.align = 'center'
bar_cux.chart.left[0].axis_label = ""
```

I think that it would be more consistent or either remove the access to those objects/properties also in `cuxfilter.charts.bar`, or give access back to those methods. I do personally prefer the second option, because it allowed to do things as follows:

![image](https://user-images.githubusercontent.com/26169771/196667166-75fd04f7-d36d-4b71-a7a6-2bb6d508934d.png)

Now, if I want to keep the title in the chart, it seems that it needs to be inside a colapsable widget:

![image](https://user-images.githubusercontent.com/26169771/196669296-6ecbef2b-a963-439d-8a78-5ee818d358e0.png)

I could yet invoke `stacked_lines_cux.view()[0]`, but the title would not be visible anymore:

![image](https://user-images.githubusercontent.com/26169771/196669465-a849f290-b5b4-4c94-95c0-6434026fa275.png)

That is why I would prefer to still have access to those objects/properties. It gives me more fine control to my charts. (if there is an alternative way to do the same, please let me know). Thanks!

**Environment details (please complete the following information):**
RAPIDS 22.10 from DockerHub/rapidsai

**Comment by AjayThorve** [comment]
Hi @miguelusque, thanks for raising this issue. There a few things to note here: 

- dynamic height/width was introduced a few version back to support layouts: https://docs.rapids.ai/api/cuxfilter/stable/layouts/Layouts.html, No longer needs width/height properties in a dashboard, and can be adjusted via dashboard layout property. 
- When the dashboard is generated via `d.app()` or `d.show()`, all the charts are resizable.
- Also the colapsible widget was introduced to make the dashboard more dynamic(resizable).

I would prefer option 1, as to completely remove the access to the chart properties, since the aim of cuxfilter is to generate dashboards with minimal complexity. 

Your usecase if I am not wrong, focusses on generating static charts, and you would prefer more control over all aspects of the chart, and for that there definitely are better alternatives now, compared to the time we implemented access to the above chart properties. 

[hvplot](https://github.com/holoviz/hvplot) directly support cudf, and could be a much better option for your usecase.

Here's how hvplot would work with cudf, with the above example:

1. 
``` python

import hvplot.cudf
import cudf
import cupy as cp
from bokeh.models import Title

n = 100000                           # Number of points
start = 1456297053                   # Start time
end = start + 60 * 60 * 24

df = cudf.DataFrame({'x': cp.linspace(start, end, n), 'y':cp.random.normal(0, 0.3, size=n).cumsum() + 50})

def update_chart_properties(plot, element):
    plot.handles['plot'].title.align = "center"
    
#use rasterize=True for big datasets, to use datashader for rendering
df.hvplot.line(x='x', y='y',  title="ECG STREAM", rasterize=True, width=500,  height=500).opts(hooks=[update_chart_properties])
```
![bokeh_plot (1)](https://user-images.githubusercontent.com/20476096/197030477-5c110ead-0bf4-473a-92b3-e2df437c5f24.png)

Let me know if you need more clarification, would be happy to help out with hvplot, since the documentation with cudf comaptibility is still scarce, but most pandas equivalent examples should work regardless.


cc @exactlyallan
