### ISSUE TITLE
[IMPROVEMENT] Add wheel builds to cuxfilter

### ISSUE THREAD

**Issue by AjayThorve** [rapidsai/cuxfilter#491]
Follow [this](https://github.com/rapidsai/ops/issues/2572) guide to add wheels builds to cuxfilter.

- [x] Transition CI to GHA from Jenkins: The wheel builds use Github Actions.
- [x] Remove usage of versioneer: Various aspects of versioneer's operation and generated versions are incompatible with other parts of the Python ecosystem.
- [x] Migrate as much logic as possible from setup.py to pyproject.toml
- [ ] Add wheels GHA workflows

cc @exactlyallan @bdice 

edit: updated checklist as per suggestion

**Comment by bdice** [comment]
A couple notes:

1. You only need to use scikit-build if you have C++ built components. You can think of scikit-build as a bridge between Python build tools and CMake (for CUDA/C++ components). So you can skip that here.
2. I shared these links in Slack but figured they could be useful here too:
  - If you need examples of PRs where the `pyproject.toml` changes happened for other packages, see this list: https://github.com/rapidsai/kvikio/pull/194#issuecomment-1511888918
  - There's a series of PRs named "Stop using versioneer to manage versions" across repos: https://github.com/search?q=org%3Arapidsai+%22Stop+using+versioneer%22&type=pullrequests

Your best model to follow might be pure Python packages like `dask-cudf` because those are migrated but don't use scikit-build.

Also maybe there is a good opportunity for some cleanup of the Python code as a whole, I saw some bits while reviewing the build system like [Makefile](https://github.com/rapidsai/cuxfilter/blob/branch-23.08/python/Makefile) and [record.txt](https://github.com/rapidsai/cuxfilter/blob/branch-23.08/python/record.txt) that seem safe to remove.
