### ISSUE TITLE
GTC demo port to 80

### ISSUE THREAD

**Issue by dkim777** [rapidsai/cuxfilter#7]
My company only allows port 80 and 443 oubound.
anyway to make this demo work on port 80?
I've tried to change config.jason  "demos_serve_port_external": 80"  
and   also mapping  -p 80:3005   neither works.
any other internal code I have to change to port 80?
Thanks

**Comment by AjayThorve** [comment]
So there are two external points that need to be mapped, one is the cuXfilter server(default:3000)(which is a node app that manages cuXfilter server requests). The other is the demo, which runs on 3005. Since the demo runs on the browser and tries to create a socket connection with server-ip:3000, you need to map both the points to a usable port.

One thing you can do is run the demo locally and not access through server-ip:3005, and map the cuXfilter server at 3000 to port 80, which would require root privileges or a work around(see this -> https://stackoverflow.com/questions/16573668/best-practices-when-running-node-js-with-port-80-ubuntu-linode).

**Comment by exactlyallan** [comment]
See latest update to an nginx server that addresses port issues.
